brands:
  - name: BMW
    featured: true
    slugs:
      autoscout24: bmw
      theparking: bmw
      autohero: bmw
      autotrader: BMW
      blocket: BMW
      mobile_de: "3500"
      auto24: "4"

  - name: Mercedes-Benz
    featured: true
    slugs:
      autoscout24: mercedes-benz
      theparking: mercedes-benz
      autohero: mercedes-benz
      autotrader: Mercedes-Benz
      blocket: Mercedes-Benz
      mobile_de: "17200"
      auto24: "12"

  - name: Audi
    featured: false
    slugs:
      autoscout24: audi
      theparking: audi
      autohero: audi
      autotrader: Audi
      blocket: Audi
      mobile_de: "1900"
      auto24: "2"

  - name: Porsche
    featured: true
    slugs:
      autoscout24: porsche
      theparking: porsche
      autohero: porsche
      autotrader: Porsche
      blocket: Porsche
      mobile_de: "20100"
      auto24: "140"

  - name: Jaguar
    featured: true
    slugs:
      autoscout24: jaguar
      theparking: jaguar
      autohero: jaguar
      autotrader: Jaguar
      blocket: Jaguar
      mobile_de: "11600"
      auto24: "36"

  - name: Land Rover
    featured: true
    slugs:
      autoscout24: land-rover
      theparking: land-rover
      autohero: land-rover
      autotrader: Land Rover
      blocket: Land Rover
      mobile_de: "15600"
      auto24: "42"

  - name: Volvo
    featured: false
    slugs:
      autoscout24: volvo
      theparking: volvo
      autohero: volvo
      autotrader: Volvo
      blocket: Volvo
      mobile_de: "25100"
      auto24: "10"

  - name: Tesla
    featured: true
    slugs:
      autoscout24: tesla
      theparking: tesla
      autohero: tesla
      autotrader: Tesla
      blocket: Tesla
      mobile_de: "27300"
      auto24: "642"

  - name: Lexus
    featured: false
    slugs:
      autoscout24: lexus
      theparking: lexus
      autohero: lexus
      autotrader: Lexus
      blocket: Lexus
      mobile_de: "15400"
      auto24: "35"

  - name: Maserati
    featured: true
    slugs:
      autoscout24: maserati
      theparking: maserati
      autohero: maserati
      autotrader: Maserati
      blocket: Maserati
      mobile_de: "16800"
      auto24: "85"

  - name: Alfa Romeo
    featured: true
    slugs:
      autoscout24: alfa-romeo
      theparking: alfa-romeo
      autohero: alfa-romeo
      autotrader: Alfa Romeo
      blocket: Alfa Romeo
      mobile_de: "900"
      auto24: "1"

  - name: Ferrari
    featured: true
    slugs:
      autoscout24: ferrari
      theparking: ferrari
      autohero: ferrari
      autotrader: Ferrari
      blocket: Ferrari
      mobile_de: "8600"
      auto24: "30"
